site:
  title: Docsvision Docs
  url: https://docsvision.github.io/docs-playbook/
  start_page: webclient:user:welcome.adoc
  robots: allow
content:
  sources:
  - url: https://github.com/docsvision/docstest.git
    branches: [main, WC*]
ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
  - path: ui.yml
    contents: |
      static_files: [ search.html ]
  - path: search.html
    contents: |
      <!DOCTYPE html>
      <html lang="ru">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <title>Добро пожаловать в документацию Docsvision! :: Docsvision Docs</title>
          <link rel="canonical" href="/docs-playbook/search.html">
          <meta name="generator" content="Antora 2.3.4">
          <link rel="stylesheet" href="/docs-playbook/_/css/site.css">
          <script>var uiRootPath = '/docs-playbook/_'</script>
      	<script async src="/docs-playbook/_/js/vendor/fess-ss.min.js"></script>
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/docsearch.js@2.6/dist/cdn/docsearch.min.css"
      />
        </head>
        <body class="article">
      <header class="header">
        <nav class="navbar">
          <div class="navbar-brand">
            <a class="navbar-item" href="https://docsvision.github.io/docs-playbook">Docsvision Docs</a>
      	  <div class="navbar-item hide-for-print">
              <input id="search-input" type="text" placeholder="Искать">
            </div>
      	  <div class="navbar-item hide-for-print">
      			<form action="https://docsvision.github.io/docs-playbook/search.html" method="get">
      				<input type="text" name="q">
      				<input type="submit" value="Search">
      			</form>
            </div>
            <button class="navbar-burger" data-target="topbar-nav">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>
          <div id="topbar-nav" class="navbar-menu">
            <div class="navbar-end">
              <a class="navbar-item" href="#">Домой</a>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="#">Купить</a>
                <div class="navbar-dropdown">
                  <a class="navbar-item" href="#">Платформа</a>
                  <a class="navbar-item" href="#">Web-клиент</a>
                  <a class="navbar-item" href="#">Базовые объекты</a>
                </div>
              </div>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="#">Ещё что-нибудь</a>
                <div class="navbar-dropdown">
                  <a class="navbar-item" href="#">Пункт 1</a>
                  <a class="navbar-item" href="#">Пункт 2</a>
                  <a class="navbar-item" href="#">Пункт 3</a>
                </div>
              </div>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="#">Другие ресурсы</a>
                <div class="navbar-dropdown">
                  <a class="navbar-item" href="#">Например, этот репозиторий</a>
                  <a class="navbar-item" href="#">Например, сайт ДВ</a>
                  <a class="navbar-item" href="#">Например, техподдержка</a>
                </div>
              </div>
              <a class="navbar-item" href="#">Любой контент</a>
            </div>
          </div>
        </nav>
      </header>
      <div class="body">
      <article class="doc">
            <h1 class="page">Поиск по документации</h1>
      <div class="paragraph">
      <script>
        (function() {
          var fess = document.createElement('script');
          fess.type = 'text/javascript';
          fess.async = true;
          // Set the URL of FSS JS to src
          fess.src = 'https://docsvision.github.io/docs-playbook/_/js/fess-ss.min.js';
          fess.charset = 'utf-8';
          fess.setAttribute ('id', 'fess-ss');
          // Set the URL of Fess search API to fess-url
          fess.setAttribute ('fess-url', 'https://СЕРВЕР/json');
          var s = document.getElementsByTagName ('script') [0];
          s.parentNode.insertBefore (fess, s);
        }) ();
      </script>
      <fess:search></fess:search>
      </div>
      </article>
      </div>
      </main>
      <footer class="footer">
        <p>Эта страница была собрана с использованием Antora default UI.</p>
        <p>Использование исходного кода этого UI регулируется лицензией MPL-2.0.</p>
        <p>Docsvision, Docsvision 5, Web-клиент являются зарегистрированными торговыми марками компании Docsvision</p>
        <p>Любой другой текст или даже картинки-иконки и т.п.</p>
      </footer>
      <script src="/docs-playbook/_/js/site.js"></script>
      <script async src="/docs-playbook/_/js/vendor/highlight.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/docsearch.js@2.6/dist/cdn/docsearch.min.js"></script>
      <script>
        docsearch({
          // Your apiKey and indexName will be given to you once
          // we create your config
          apiKey: '223192edd0ed20028d448bb95303cf7f',
          indexName: 'DocsSearch',
          appId: 'WJDJN0MAL7', // Should be only included if you are running DocSearch on your own.
          // Replace inputSelector with a CSS selector
          // matching your search input
          inputSelector: '#search-input',
          // Set debug to true to inspect the dropdown
          debug: false,
        });
      </script>
        </body>
      </html>
asciidoc:
  attributes:
    toclevels: 10
    sectids: ''
    sectlinks: ''
    sectanchors: ''
    toc-title: Содержание
    icons: font
    figure-caption: Рисунок
    appendix-caption: Приложение
    wc: WebClient
    dv: Docsvision
    page-pagination: ''
urls:
  html_extension_style: indexify
output:
  dir: ./
runtime:
  fetch: true